# Generated by Django 5.2.3 on 2025-06-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['book_id'], name='review_book_idx'),
        ),
    ]
